secs.component("input")
secs.component("actor")
secs.component("hitboxes")
secs.component("crate")
secs.component("treasure")
secs.component("rich")
secs.component("group")
secs.component("class", { type = "none" })
secs.component("color", { rgb = false })
secs.component("sprite", { sprite = false })
secs.component("physics", { gravity = 1200, onGround = false, onOneway })
secs.component("rect", { style = "fill", rgb = { 255,255,255,255 }})
secs.component("stage", { path = "", load = false, unload = false })
secs.component("pos",  { x = 0, y = 0, z = 0, w = 0, h = 0, dx = 1, dy = 1 })
secs.component("vel",  { x = 0, y = 0, maxX = 150, maxY = 350 })
secs.component("spatialhash", { map = false })

secs.type("controllable", "input", "vel", "pos")
secs.type("rectangles", "rect", "pos")
secs.type("movable", "pos", "vel")
secs.type("actors", "actor")
secs.type("collidable", "hitboxes", "pos")
secs.type("physical", "pos", "vel")
secs.type("sprites", "sprite", "pos")