secs.component("actor")
secs.component("hitboxes")
secs.component("crate")
secs.component("treasure")
secs.component("rich")
secs.component("group")
secs.component("switch")
secs.component("projectile")
secs.component("title")
secs.component("input", { timer = 0, limit = 0.2 })
secs.component("wall", { active = false })
secs.component("camera", { target = false, x1 = 0, y1 = 0, x2 = WINDOW_WIDTH, y2 = WINDOW_HEIGHT })
secs.component("text", { text = "" })
secs.component("class", { id = 1, type = "fighter" })
secs.component("color", { rgb = false })
secs.component("sprite", { sprite = false })
secs.component("physics", { gravity = 1200, onGround = false, friction = true, onOneway = false })
secs.component("rect", { style = "fill", rgb = { 255,255,255,255 }})
secs.component("stage", { path = "", load = false, unload = false })
secs.component("pos",  { x = 0, y = 0, z = 0, w = 0, h = 0, dx = 1, dy = 1 })
secs.component("vel",  { x = 0, y = 0, maxX = 150, maxY = 350 })
secs.component("spatialhash", { map = false })
secs.component("selector", { size = 1, index = 1, count = 0, limit = 0.2, group = false })

secs.type("controllable", "input", "vel", "pos")
secs.type("rectangles", "rect", "pos")
secs.type("movable", "pos", "vel")
secs.type("actors", "actor")
secs.type("collidable", "hitboxes", "pos")
secs.type("physical", "pos", "vel")
secs.type("sprites", "sprite", "pos")
secs.type("text", "text", "pos")
secs.type("walls", "wall")
secs.type("treasure", "treasure")